spring:
  application:
    name: hadoop
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/sxpdb
#server:
#  port: 9000

#hdfs:
#  path: hdfs://47.101.46.0:9000
#  username: root